[Feat/week1] 필수과제
DO-SOPT-ANDROID/Yeon-Jeen pull request #1
Opened 2023-10-12 19:08 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #1주차 필수과

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 로그인 구현
- 회원가입 구현
-메인 창 구현
## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/Yeon-Jeen/assets/144861180/c6e5e8ab-8489-400a-9ce2-923488b974b1

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
살짝 끄적끄적 해보자면...ㅎ 전공자이지만 전공을 버리고 산지 언 3년(?) 개린이(개발어린이) 그 자체입니다ㅎ 아낌없는 충고와 조언 부탁드립니당:)

2023-10-12 23:54 UTC, KwakEuiJin requested changes
과제하느라 너무 고생 많으셨습니다~!! 리뷰 보시고 수정 or 코멘트 부탁드려요~!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/build.gradle
>  }
필요없는 줄바꿈은 삭제! 부탁드려요~!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +        }
scope함수를 사용한다면 변수선언을 하지 않아도 괜찮습니다! 

[Kotlin Scope 함수](https://kotlinlang.org/docs/scope-functions.html#function-selection)

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +        setContentView(view)
```suggestion
        setContentView(binding.root)
```

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +        setContentView(view)
요렇게 하면 굳이 변수 선언할 필요 없겠죠?! 물론 정답은 아닙니다!! 저런 방법도 있다는 거니 참고해주시면 최고~!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +    }
요 부분 함수가 기능이 의도와는 다른 것 같네요~!! 다시 한번 살펴보시고 수정 부탁드립니당

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +        }
추가적으로 로그인 성공 토스트가 없는 것 같네요!? 확인해주시고 추가 부탁드려요

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/MainActivity.kt
> +        binding.tAD3.text = "$address"
ID에 숫자는 최대한 금지해주시는게 추후 유지보수시에 헷갈리지 않으실거에요~!! 

아마 각 화면별로 중복되는 아이디가 있어서 숫자를 붙이신 것 같은데 어차피 Binding으로 접근하면 각 화면에 알맞는 아이디가 참조되기 때문에 숫자는 제거해주셔도 됩니다!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
>          val isNicknameValid = nickname.isNotBlank() && !nickname.matches(Regex("\\s+"))
꿀팁공유를 보시면 정규표현식에 대한 설명이 나와있으니 참고해서 수정 가능하실 때 수정 부탁드립니다!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="180dp"
layout_constraintDimensionRatio를 쓰셨다면 layout_width, layout_height 중에 하나는 0dp로 잡아주셔도 되요~!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="H,1:1"
```suggestion
        app:layout_constraintDimensionRatio="1"
```

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="H,1:1"
이렇게 바꿀 수도 있답니다~!!

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="40dp"
text들 string resource로 빼면 아래와 같은 이점이 있습니다.
1. 오타 방지
2. 재사용성 증가
3. 다국어 지원 유연성 증가

2023-10-12 23:54 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="40dp"
이러한 이점이 해당프로젝트에 도움이 되신다면 string resoruce 로 분리해보시면 좋을 것 같습니다 ㅎㅎ

2023-10-13 01:24 UTC, Jokwanhee reviewed
연진님~ 고생하셨습니다! 코드 잘 봤습니다~!

2023-10-13 01:24 UTC, Jokwanhee commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
>          setContentView(R.layout.activity_signup)
binding 값 할당 부분이 빠진 것 같아요!

2023-10-13 01:24 UTC, Jokwanhee commented on app/src/main/res/layout/activity_login.xml
>          android:id="@+id/logbtn1"
네이밍을 할 때 좀 더 명시적으로 진행하면 좋을 것 같아요!
로그인을 하는 버튼인지.. 로그를 찍는 버튼인지.. 저로써는 엥? 뭐지? ...
추가적으로 네이밍 표기법 중 스네이크(login_button) 표기법이나 카멜 표기법(loginButton)을 따라보는 것은 어떨까요?

2023-10-13 03:14 UTC, yeonjeen commented on app/build.gradle
>  }
ctrl+alt+L 습관화 하겠슴다!!

2023-10-13 03:53 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +        setContentView(view)
아핳 감사합니다! 코드가 훨씬 간단해지겠네요!

2023-10-13 11:39 UTC, emjayMJkim reviewed
과제하느라 고생했어~!!

2023-10-13 11:39 UTC, emjayMJkim commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +                Toast.makeText(this, "로그인에 실패하셨습니다.", Toast.LENGTH_SHORT).show()
getString(R.string.~~)으로 string 리소스 파일로 따로 분리하면 하드코딩을 피할 수 있습니다!!

2023-10-13 11:39 UTC, emjayMJkim commented on app/src/main/res/layout/activity_login.xml
>          android:text="Welcome to SOPT"
이 부분도 string 추출해주는 것이 더 좋을 것 같습니다!

2023-10-13 11:39 UTC, emjayMJkim commented on app/src/main/res/layout/activity_login.xml
>          android:id="@+id/title1"
변수명을 좀 더 직관적으로 해주시면 좋을 것 같아요

2023-10-15 07:27 UTC, merged

2023-10-15 11:05 UTC, KwakEuiJin commented
approve 전에 머지가 된 것 같은데 담부터는 조심해주세요,
수정내역은 확인되었습니다.