[Feat/week2] 필수과제
DO-SOPT-ANDROID/Yeon-Jeen pull request #2
Opened 2023-10-27 14:40 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 바텀네비게이션, 프레그먼트 구현
- 리사이클러뷰 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/DO-SOPT-ANDROID/Yeon-Jeen/assets/144861180/1aff352c-f7ec-4d30-beab-aaabb6780b3a

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳s
일단 처음 구현해보는 점들이 너무 많아서 어려운 점들도 많았는데 마지막까지 많은 도움을 주신 분들께 진심으로 감사드립니다!!(꾸벅) 그리고 코드 리뷰 많이 많이 달아주세요 저는 약간 많이 달릴 수록 감동이더라고요..ㅎ

2023-10-27 14:46 UTC, Jokwanhee reviewed
과제 제출하시느라 고생하셨습니다! 코드 잘 보았습니다 🐼

2023-10-27 14:46 UTC, Jokwanhee commented on app/src/main/res/drawable/fubao11.jpg
귀여운 판다네요!

2023-10-27 14:46 UTC, Jokwanhee commented on app/src/main/res/layout/item_friend.xml
> +        android:text="나는 연진이야 잘 부탁해"
string resource 사용 권장합니다!

2023-10-27 14:46 UTC, Jokwanhee commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +
ctrl + alt + L 를 사용해서, Reformat Code 부탁드립니다!

2023-10-27 14:46 UTC, DoReMinWoo reviewed
너무 고생 많으셨어요!!!!

2023-10-27 14:46 UTC, DoReMinWoo commented on app/src/main/java/com/cookandroid/week1/Friend.kt
> +
쉬프트 + 알트 + L을 사용하신다면 엔터나 띄어쓰기를 자동으로 정렬할 수 있어요

2023-10-27 14:46 UTC, DoReMinWoo commented on app/src/main/java/com/cookandroid/week1/MainActivity.kt
> +        }
함수화 하면 좋을 것 같아요!

2023-10-27 14:46 UTC, DoReMinWoo commented on app/src/main/java/com/cookandroid/week1/MyPageFragment.kt
> +        binding.tAD3.text = address
스코프 함수에 대해서 공부하신다면 좋은 코드가 될 것 같아요!

2023-10-27 14:46 UTC, DoReMinWoo commented on app/src/main/res/drawable/fubao2.jpg
푸바오 너무 귀여워요!!!!!!!

2023-10-29 04:45 UTC, emjayMJkim reviewed
과제 하느라 수고했어!!

2023-10-29 04:45 UTC, emjayMJkim commented on app/src/main/res/layout/item_friend.xml
> +        android:text="나는 연진이야 잘 부탁해"
Alt+enter 로 쉽게 할 수 있습니다~~

2023-10-29 04:45 UTC, emjayMJkim commented on app/src/main/res/layout/fragment_my_page.xml
> +        android:id="@+id/tID4"
id 네이밍을 좀 더 알아보기 쉽게 하면 좋을 것 같아요!!

2023-10-29 04:45 UTC, emjayMJkim commented on app/src/main/java/com/cookandroid/week1/MyProfile.kt
> +sealed class A{
sealed class 좋습니당~~ 
여기도 네이밍을 좀 더 알아보기 쉽게 해주면 더 좋을 것 같아요!!

2023-10-29 04:45 UTC, emjayMJkim commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +    }
```suggestion
    override fun getItemCount() = items.size + 1
    
```

참고: 이런 식으로 쓸 수도 있답니당

2023-10-29 06:30 UTC, KwakEuiJin requested changes
2주차 과제하시느라 고생하셨습니다~!! 확인후 수정 부탁드려요~!!

2023-10-29 06:30 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +    }
중첩클래스 활용을 하시는 걸 추천드립니다. 자세한 내용은 [해당 링크](https://shinjekim.github.io/kotlin/2019/08/29/Kotlin-%EB%82%B4%EB%B6%80-%ED%81%B4%EB%9E%98%EC%8A%A4(inner-class)%EC%99%80-%EC%A4%91%EC%B2%A9-%ED%81%B4%EB%9E%98%EC%8A%A4(nested-class)/)를 참조해보세요!

2023-10-29 06:30 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +    RecyclerView.Adapter<RecyclerView.ViewHolder>() {
List Type이 Any면 안될 것 같네요!!

2023-11-01 14:00 UTC, yeonjeen commented on app/src/main/res/layout/item_friend.xml
> +        android:text="나는 연진이야 잘 부탁해"
꿀팁 감사함당!!

2023-11-01 14:00 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +
아핳.. 잊지않겠슴다!!

2023-11-02 04:59 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/Friend.kt
> +
잊지 않고 하겠습니다!!:)

2023-11-02 05:01 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MyPageFragment.kt
> +        binding.tAD3.text = address
요즘 공부 중에 있어요!! 스코프 함수 사용해서 한 번 수정해보겠습니다!

2023-11-02 05:02 UTC, yeonjeen commented on app/src/main/res/layout/fragment_my_page.xml
> +        android:id="@+id/tID4"
네이밍.. 열심히 고민해보겠습니다!!ㅎㅎ

2023-11-02 05:02 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +    }
오오 좋은 정보 감사해요!! 확실히 코드를 단순화하게 만들 필요가 있는 것 같아요

2023-11-02 05:03 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
> +    RecyclerView.Adapter<RecyclerView.ViewHolder>() {
아핳.. 수정해보겠습니다!

2023-11-02 06:47 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MainActivity.kt
> +        }
함 도전해보겠습니다..!

2023-11-03 07:35 UTC, KwakEuiJin approved these changes

2023-11-03 07:37 UTC, merged