[Feat/week4] 필수과제
DO-SOPT-ANDROID/Yeon-Jeen pull request #4
Opened 2023-11-17 13:28 UTC by yeonjeen

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- baseurl이 buildconfig에 적용X > 시간이 지나니까 적용됌

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 회원가입과 로그인 서버통신
- 로그인 성공 or 실패 시 Toast 메세지
- HomeFragment에 Open API 적용

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/Yeon-Jeen/assets/144861180/da8c8e20-78b5-47c8-9132-b25f39219a9b

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
너무 어려웠지만 어려운만큼 많이 공부하고 배우는 시간이었습니다!! 또 (많이)부족한 저를 위해 많은 시간을 함께 해주신 코끼리조 여러분께 감사드립니당:) (꾸벅)(감사)(감동)

2023-11-17 14:22 UTC, Jokwanhee reviewed
고생하셨습니다!! 매번 발전하는 코드 보기 좋습니다!! 🐼

2023-11-17 14:22 UTC, Jokwanhee commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +                            "로그인에 성공하셨습니다.",
string resource 파일 사용을 적극 권장드립니다!!!

2023-11-17 14:22 UTC, Jokwanhee commented on app/src/main/java/com/cookandroid/week1/ProfileRequest.kt
> +
reformatting 습관을 들이셔야 할 것 같아요! ktlint 와 같은 정적분석도구를 사용해보면서 깔끔한 코드를 만들어가는 방향을 잡으시면 좋을 것 같습니당!

2023-11-17 14:22 UTC, Jokwanhee commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
>          private val ivProfile: ShapeableImageView = itemView.findViewById(R.id.iv_profile)
성능 문제를 유발하는 findViewById 를 사용하지 않기 위해서 ViewBinding 을 사용하는데, 해당 부분에서도 사용할 수 있어요!

2023-11-19 07:26 UTC, KwakEuiJin requested changes
리뷰 확인후에 코멘트 및 수정 부탁드립니다~!!

2023-11-19 07:26 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +
코드정렬 부탁드립니다~!

2023-11-19 07:26 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +                                )
클래스네임이 A면 왜 안좋을지 생각해보시구 의견남겨주시면 좋을 것 같아요~!! +수정

2023-11-19 07:26 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
> +                }
printStackTrace은 릴리즈 상황에서도 로그가 보이기 때문에 Log.e를 사용하는 것이 좋습니다~!!

2023-11-19 07:26 UTC, KwakEuiJin commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
> +                    else {
주석제거해주세용~!!

2023-11-19 11:48 UTC, emjayMJkim reviewed
진짜 서버통신 수고했어~

2023-11-19 11:48 UTC, emjayMJkim commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +                    t.printStackTrace()
Log 사용을 추천드립니당~

2023-11-20 10:26 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/LoginActivity.kt
> +                            "로그인에 성공하셨습니다.",
xml파일만 생각했네용..! 수정하겠습니다!!

2023-11-21 06:30 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/ProfileRequest.kt
> +
협업을 준비하면서 필요성을 많이 느끼고 있습니다..!! 조언 참고해서 사용해보겠습니다!!

2023-11-21 06:39 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/MultiViewTypeAdapter.kt
>          private val ivProfile: ShapeableImageView = itemView.findViewById(R.id.iv_profile)
아하! 감사합니다! 수정했습니다:)

2023-11-21 06:44 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +
넵! 수정했습니다~

2023-11-21 06:47 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +                                )
직관적으로 어떤 리스트인지 확인하기 어렵고 가독성이 떨어질 수 있다고 생각합니다!! 리스트의 의미를 닮을 수 있는 네임으로 수정하겠습니다!!

2023-11-21 06:55 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
> +                }
수정했습니다~

2023-11-21 06:55 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/HomeFragment.kt
> +                    t.printStackTrace()
수정했습니다~

2023-11-21 06:55 UTC, yeonjeen commented on app/src/main/java/com/cookandroid/week1/SignUpActivity.kt
> +                    else {
제거했습니다!!:)

2023-11-21 10:28 UTC, KwakEuiJin approved these changes

2023-11-23 13:12 UTC, merged